trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: UseNode@1
  inputs:
    checkLatest: true
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    configuration: 'Release'
    clean: true